name: "Sagemaker_batch_transform_job"

description: "Sagemaker batch transform job"
author: gowtam.degapudi@ascentt.com
branding:
  icon: "file"
  color: "white"

runs:
  using: "composite"
    - id: Batch transform job
      shell: bash
      run: python3 batch_transform.py
