name: 'Batch_Transform_GitHub_Actions'
on:
  workflow_dispatch:
  #push:
  #branches: 
  #pull_request:

jobs:
  Sagemaker_batch_transform:
    name: 'Sagemaker_batch_transform'
    runs-on: ubuntu-22.04

    steps:
      - name: 'Checkout'
        uses: actions/checkout@v4

      - name: 'Set up AWS Credentials'
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{secrets.AWS_SESSION_TOKEN}}  
          aws-region: us-east-1  # or your preferred AWS region


      - name: 'Deploying batch transform job'
        uses: ./
        
